---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
  annotations:
    flux.weave.works/ignore: "true"
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:~1.4
spec:
  timeout: 0
  chart:
    repository: https://stefanprodan.github.io/k8s-podinfo
    name: podinfo
    version: 1.4.2
  values:
    image:
      repository: quay.io/stefanprodan/podinfo
      tag: 1.4.1
    replicaCount: 1
