---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: test
  annotations:
    flux.weave.works/ignore: "true"
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:~4.0
spec:
  releaseName: redis
  timeout: 500
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: redis
    version: 4.2.10
  values:
    image:
      repository: bitnami/redis
      tag: 4.0.11
    service:
      type: ClusterIP
      port: 6379
    cluster:
      enabled: false
    usePassword: false
    master:
      persistence:
        enabled: false
